# permissions for end users to edit cleanupoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleanupoperator-editor-role
rules:
- apiGroups:
  - cleanup.ibm.com
  resources:
  - cleanupoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cleanup.ibm.com
  resources:
  - cleanupoperators/status
  verbs:
  - get
