# permissions for end users to view cleanupoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleanupoperator-viewer-role
rules:
- apiGroups:
  - cleanup.ibm.com
  resources:
  - cleanupoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cleanup.ibm.com
  resources:
  - cleanupoperators/status
  verbs:
  - get
