
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cleanup.ibm.com
  resources:
  - cleanupoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cleanup.ibm.com
  resources:
  - cleanupoperators/finalizers
  verbs:
  - update
- apiGroups:
  - cleanup.ibm.com
  resources:
  - cleanupoperators/status
  verbs:
  - get
  - patch
  - update
