apiVersion: v1
kind: Pod
metadata:
  name: pod-devtest-blk-01
spec:
  volumes:
  - name: test-vol
    persistentVolumeClaim:
        claimName: devtest-blk-pvc
  containers:
  - name: devtest-demo-container
    image: ubuntu:latest
    command: ["sh"]
    args: ["-c", "while true; do echo date; sleep 10; done"]
    volumeDevices:
    - name: test-vol
      devicePath: "/dev/xvdc"