kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devtest-blk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Block
  storageClassName: sat-local-block-gold